# TODO: update all of this
# Ok, slack's apis + integrations are a big mess.  This was much simpler a few
# years ago.  Some learnings:
#
# - Distributing as a slack app isn't going to work.  That seems built around
#   externally-hosted servers.  You get the web-api credentials during this
#   oauth-like flow that happens when a team clicks the "add app" button.
# - Wait!  No!  In the app config, under "Add features + functionality"
#   > Permissions > Bot User OAuth Access Token, there's a bot user oauth token
#   that seems to work for accessing the web api.
#

redis_host: localhost:6379

bot_name: bub

# Rack options
Port: 65222

# Bot oauth token
bot_oauth_token: abcd-123456

slack_channel: general

# H'ok, so:
# deploy_targets lists each codebase.  Deploy defines how to deploy.  Any string
# in here will get run through erb.  Some parameters that will be provided to erb
# are:
#  - server
#  - branch
#
# deploy types are:
#  - script (just some local script to run; should be in git repo?)
#  - git (a git remote to push to)
#  - http (some web callback to hit)

deploy_targets:
  core:
    git: 'git@github.com:MyCo/foo.git'
    deploy:
      git: 'git@beta.aptible.com:myco-<%=server %>/foo-rails.git'
    #default_branch: develop - TODO not yet supported
  web:
    git: 'git@github.com:MyCo/web.git'

    # Script params: repo_dir, branch, server to deploy to
    # (repo should already be on the right branch)
    deploy:
      script: 'deploy_web.sh'
    #default_branch: develop - TODO not yet supported

servers:
  #- cannoli
  #- hotdog
  - burrito
  - gyro

